import { base44 } from '@/api/base44Client';

const SEED_WORKOUTS = [
  { title: "Perfect Push-Up", description: "Master the classic push-up with proper form. Keep your core tight, elbows at 45 degrees, and lower until your chest nearly touches the ground.", category: "strength", difficulty: "beginner", target_muscle: "chest", creator_name: "Alex Chen", likes: 342, saves: 89, attempts_count: 1250, is_pro: false, is_verified_coach: false, duration_seconds: 15, pass_threshold: 75, thumbnail_url: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&h=800&fit=crop" },
  { title: "Explosive Box Jump", description: "Build lower body power with this explosive box jump. Focus on landing softly with knees bent.", category: "hiit", difficulty: "intermediate", target_muscle: "legs", creator_name: "Maya Johnson", likes: 218, saves: 56, attempts_count: 890, is_pro: false, is_verified_coach: false, duration_seconds: 10, pass_threshold: 70, thumbnail_url: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600&h=800&fit=crop" },
  { title: "Kettlebell Swing", description: "Full-body power movement. Drive hips forward, keep arms straight, let the bell float to chest height.", category: "strength", difficulty: "intermediate", target_muscle: "full_body", creator_name: "Jake Rivera", likes: 456, saves: 123, attempts_count: 2100, is_pro: false, is_verified_coach: false, duration_seconds: 20, pass_threshold: 72, thumbnail_url: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&h=800&fit=crop" },
  { title: "Burpee Challenge", description: "The ultimate full-body cardio move. Drop to the floor, push up, jump up with arms overhead.", category: "cardio", difficulty: "advanced", target_muscle: "full_body", creator_name: "Sarah Kim", likes: 189, saves: 41, attempts_count: 670, is_pro: false, is_verified_coach: false, duration_seconds: 12, pass_threshold: 80, thumbnail_url: "https://images.unsplash.com/photo-1549576490-b0b4831ef60a?w=600&h=800&fit=crop" },
  { title: "Deep Squat Hold", description: "Mobility and strength combined. Sit deep into a squat, chest up, heels down.", category: "mobility", difficulty: "beginner", target_muscle: "lower_body", creator_name: "Liam Foster", likes: 275, saves: 98, attempts_count: 1800, is_pro: false, is_verified_coach: false, duration_seconds: 30, pass_threshold: 70, thumbnail_url: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600&h=800&fit=crop" },
  { title: "Turkish Get-Up", description: "Complex movement testing full-body stability. Rise from floor to standing with weight overhead.", category: "strength", difficulty: "advanced", target_muscle: "full_body", creator_name: "Nadia Petrov", likes: 134, saves: 67, attempts_count: 320, is_pro: false, is_verified_coach: false, duration_seconds: 45, pass_threshold: 80, thumbnail_url: "https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=600&h=800&fit=crop" },
  { title: "Warrior Flow Sequence", description: "Smooth transition through Warrior I, II, and III. Focus on balance, breathing, and alignment.", category: "yoga", difficulty: "intermediate", target_muscle: "full_body", creator_name: "Priya Sharma", likes: 512, saves: 201, attempts_count: 3200, is_pro: false, is_verified_coach: false, duration_seconds: 40, pass_threshold: 70, thumbnail_url: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&h=800&fit=crop" },
  { title: "Muscle-Up Progression", description: "The king of calisthenics movements. Explosive pull, transition over the bar, press to extension.", category: "calisthenics", difficulty: "advanced", target_muscle: "upper_body", creator_name: "Marcus Lee", likes: 389, saves: 156, attempts_count: 450, is_pro: false, is_verified_coach: false, duration_seconds: 15, pass_threshold: 85, thumbnail_url: "https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=600&h=800&fit=crop" },
  { title: "Pro: Push-Up Form Correction", description: "Common push-up mistakes and how to fix them. Proper hand placement, core engagement, and breathing.", category: "strength", difficulty: "beginner", target_muscle: "chest", creator_name: "Coach Torres", likes: 890, saves: 345, attempts_count: 4200, is_pro: true, is_verified_coach: true, duration_seconds: 20, pass_threshold: 70, thumbnail_url: "https://images.unsplash.com/photo-1550345332-09e3ac987658?w=600&h=400&fit=crop" },
  { title: "Pro: Squat Mechanics Masterclass", description: "Deep dive into squat biomechanics. Ankle mobility, hip hinge, knee tracking, and spine neutrality.", category: "strength", difficulty: "intermediate", target_muscle: "lower_body", creator_name: "Dr. Lin Wei", likes: 670, saves: 289, attempts_count: 3100, is_pro: true, is_verified_coach: true, duration_seconds: 35, pass_threshold: 75, thumbnail_url: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600&h=400&fit=crop" },
  { title: "Pro: HIIT Technique Optimization", description: "Maximize HIIT results with proper movement patterns. Speed without sacrificing form.", category: "hiit", difficulty: "advanced", target_muscle: "full_body", creator_name: "Coach Amir", likes: 445, saves: 198, attempts_count: 1800, is_pro: true, is_verified_coach: true, duration_seconds: 25, pass_threshold: 80, thumbnail_url: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&h=400&fit=crop" },
  { title: "Pro: Mobility Reset Routine", description: "15-minute daily mobility routine to improve range of motion and prevent injuries.", category: "mobility", difficulty: "beginner", target_muscle: "full_body", creator_name: "Dr. Sarah Mills", likes: 1200, saves: 567, attempts_count: 8900, is_pro: true, is_verified_coach: true, duration_seconds: 30, pass_threshold: 65, thumbnail_url: "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&h=400&fit=crop" },
];

export async function seedWorkoutsIfEmpty() {
  const existing = await base44.entities.Workout.list('-created_date', 1);
  if (existing.length > 0) return;
  await base44.entities.Workout.bulkCreate(SEED_WORKOUTS);
}